language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli --silent
  - ng build --prod
cache:
  directories:
    - "node_modules"

before_deploy:
  - cp ./src/server/** dist/
  - cd ./dist

deploy:
  provider: azure_web_apps
#  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
#  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
#  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
#  slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
  on: master
